### ISSUE TITLE
Bots server gets stuck after changing map

### ISSUE THREAD

**Issue by zotil** [actionquake/aq2-tng#136]
We have a bot server running that get stuck randomly after changing map, it could be in the first map of the rotation, 4th, etc.

I noted that the problem happens when one or more human players play with the bots, after leaving and the map change comes, the load of the next map get stuck and q2proded goes to cpu usage in range of 80-99%

bots.env:
```env
TEAM_1_NAME=Red Devils
TEAM_2_NAME=Blue Devils
TEAM_3_NAME=Green Devils
TEAM_1_SKIN=male/ctf_r
TEAM_2_SKIN=male/ctf_b
TEAM_3_SKIN=male/ctf_g
HOSTNAME=AQ2World Chile [bots DM]
PORT=27912
MAXCLIENTS=16
RCON_PASSWORD=***
TIMELIMIT=15
FRAGLIMIT=50
ROUNDLIMIT=0
FULLMAPS=TRUE
DMFLAGS=16
TEAMPLAY=0
MATCHMODE=0
ROUNDTIMELIMIT=2
ROTATION=gangsta,terminal,urban4,beer,wfall,country,urban3,urban2,ground3,bwcity2,urban,country2,tokyo,countryside
SV_FPS=10
LOGFILE_FLUSH=2
LOGFILE=2
LOGFILE_NAME=bots
LIMCHASECAM=0
SERVERTARGETDIR=aq2world_chile/bots_27912/
AWS_ACCESS_KEY=***
AWS_SECRET_KEY=***
STAT_LOGS=0
FORCE_SKIN=""
STAT_APIKEY=none
IRC_BOT=0
ETE_ENHANCEDSLIPPERS=1
SV_ANTILAG=1
SV_ANTILAG_INTERP=0
G_SPAWN_ITEMS=1
DEADTALK=1
LLSOUND=1
ZOOM_COMP=1
AM=1
AM_BOTCOUNT=8
```

I attach the log of the server from start, playing to get stuck.

[bots_log.txt](https://github.com/actionquake/aq2-tng/files/12580950/bots_log.txt)

**Comment by darkshade9** [comment]
I think I may know what the issue is @zotil , in your docker-compose.yaml file, what version of game server are you running?  It will be the tag of the docker image.

**Comment by zotil** [comment]
Actually we are running aqtiongame/server:v44, q2proded r1~42d4d91 is in this image

**Comment by darkshade9** [comment]
Try `v45-rc2` for now instead of `v44`

**Comment by zotil** [comment]
I changed the version, has been working fine for the last ~48 hours. Thanks!
