### ISSUE TITLE
Espionage impacting other modes?

### ISSUE THREAD

**Issue by MVarland** [actionquake/aq2-tng#173]
The condump below is from a Teamplay Matchmode server

Terminal
by WizardExt
CL adding cvarsync: cl_antilag, 1
CL adding cvarsync: cl_indicators, 1
CL adding cvarsync: cl_xerp, 2
CL adding cvarsync: cl_spectatorhud, 1
CL adding cvarsync: cl_spectatorkillfeed, 0
_FragBait entered the game
AQ2: The Next Generation v2.83 2023-12-20 ae25a56
https://www.aq2world.com -- https://discord.aq2world.com
noname
Matchmode: Teamplay

Fraglimit: none  Timelimit: none
Roundlimit: none  Roundtimelimit: 2
Chase Cam Disallowed
Vote Types: Map & Kick

Hit TAB to open the Team selection menu
version is read-only.
_FragBait joined RED.
You joined Team 1 (RED).
]teamskin male/ctf_r
Espionage skins are set in the .esp file

**Comment by darkshade9** [comment]
Yep this is a bug, will fix

**Comment by darkshade9** [comment]
Fixed in https://github.com/actionquake/aq2-tng/commit/834cff96b35ca580a72a292dcfcabde3d4757d15
